AllowedOrigins:
  - "http://localhost:3000"
  - "http://localhost:3001"
  - "http://localhost:3002"

Database:
  User: "postgres"
  Password: "empty"
  Database: "back"
  Host: "localhost"
  Port: 5432

GitHub:
  ClientId: "123"
  ClientSecret: "123"
  RedirectUrl: "https://dessert.dev/"
