AllowedOrigins:
  - "http://localhost:3000"
  - "http://localhost:5000"
  - "https://dessert.dev"
  - "https://develop.dessert.dev"
  - "https://dessert.vercel.app"

GitHub:
  ClientId: ""
  ClientSecret: ""
  RedirectUrl: "https://dessert.dev/"

Database:
  User: "back"
  Password: ""
  Database: "back"
  Host: "x2021dessert3090231965000.northeurope.cloudapp.azure.com"
  Port: 5432
