# Image used during the build process
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env

WORKDIR /app

COPY Dessert/Dessert.csproj .
RUN dotnet restore

COPY Dessert .
RUN dotnet publish -c Release -o out

# -----------------------------------------------------------
# Runtime starts here
# -----------------------------------------------------------

# Runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

WORKDIR /app

# Get the output build directory generated by the build layer
COPY --from=build-env /app/out .

# The configuration file needs to be mounted (docker -v)
ENTRYPOINT ["dotnet", "Dessert.dll", "start"]
