name: develop

on:
  push:
    branches:
      - develop

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_REMOTE }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Upload container to registry
        run: |
          docker build -t back .
          docker tag back ${{ secrets.REGISTRY_REMOTE }}/back:develop
          docker push ${{ secrets.REGISTRY_REMOTE }}/back:develop
