name: develop

on:
  push:
    branches:    
      - develop

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: |
        docker build -t back .
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_LOGIN }} --password-stdin ${{ secrets.REGISTRY_REMOTE }}
        docker tag back ${{ secrets.REGISTRY_REMOTE }}/back:develop
        docker push ${{ secrets.REGISTRY_REMOTE }}/back:develop
