name: develop

on:
  push:
    branches:
      - develop

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload container to registry
      run: |
        docker build -t back .
        docker login -u ${{ secrets.REGISTRY_LOGIN }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_REMOTE }}
        docker tag back ${{ secrets.REGISTRY_REMOTE }}/back:develop
        docker push ${{ secrets.REGISTRY_REMOTE }}/back:develop
