name: develop

on:
  push:
    branches:
      - develop

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@master
        with:
          login-server: dessert.azurecr.io
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -t dessert.azurecr.io/back:develop .
          docker push dessert.azurecr.io/back:develop
