name: master

on:
  push:
    branches:
      - master

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          login-server: dessert.azurecr.io
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Upload to registry
        run: |
          docker build -t dessert.azurecr.io/back:latest .
          docker push dessert.azurecr.io/back:latest
